set_property BOARD_PIN {clk_p} [get_ports {sys_clock_p}]
set_property BOARD_PIN {clk_n} [get_ports {sys_clock_n}]
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
set_property PACKAGE_PIN {R32} [get_ports {jtag_jtag_TCK}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TCK}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TCK}]
set_property PACKAGE_PIN {W36} [get_ports {jtag_jtag_TMS}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TMS}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TMS}]
set_property PACKAGE_PIN {W37} [get_ports {jtag_jtag_TDI}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDI}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDI}]
set_property PACKAGE_PIN {V40} [get_ports {jtag_jtag_TDO}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDO}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDO}]
set_property PACKAGE_PIN {AT32} [get_ports {uart_ctsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_ctsn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {uart_ctsn}]]]
set_property PACKAGE_PIN {AR34} [get_ports {uart_rtsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rtsn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rtsn}]]]
set_property PACKAGE_PIN {AU33} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {AU36} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]
set_property PACKAGE_PIN {AN30} [get_ports {sdio_sdio_clk}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_clk}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_clk}]]]
set_property PACKAGE_PIN {AP30} [get_ports {sdio_sdio_cmd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_cmd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_cmd}]]]
set_property PACKAGE_PIN {AR30} [get_ports {sdio_sdio_dat_0}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_0}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {sdio_sdio_dat_0}]]]
set_property PACKAGE_PIN {AU31} [get_ports {sdio_sdio_dat_1}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_1}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_1}]]]
set_property PACKAGE_PIN {AV31} [get_ports {sdio_sdio_dat_2}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_2}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_2}]]]
set_property PACKAGE_PIN {AT30} [get_ports {sdio_sdio_dat_3}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_3}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_3}]]]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_cmd}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_0}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_1}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_2}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_3}]
set_property PACKAGE_PIN {A10} [get_ports {pcie_REFCLK_rxp}]
set_property PACKAGE_PIN {A9} [get_ports {pcie_REFCLK_rxn}]
set_property PACKAGE_PIN {H4} [get_ports {pcie_pci_exp_txp}]
set_property PACKAGE_PIN {H3} [get_ports {pcie_pci_exp_txn}]
set_property PACKAGE_PIN {G6} [get_ports {pcie_pci_exp_rxp}]
set_property PACKAGE_PIN {G5} [get_ports {pcie_pci_exp_rxn}]
set_property BOARD_PIN {leds_8bits_tri_o_0} [get_ports {led[0]}]
set_property BOARD_PIN {leds_8bits_tri_o_1} [get_ports {led[1]}]
set_property BOARD_PIN {leds_8bits_tri_o_2} [get_ports {led[2]}]
set_property BOARD_PIN {leds_8bits_tri_o_3} [get_ports {led[3]}]
set_property BOARD_PIN {leds_8bits_tri_o_4} [get_ports {led[4]}]
set_property BOARD_PIN {leds_8bits_tri_o_5} [get_ports {led[5]}]
set_property BOARD_PIN {leds_8bits_tri_o_6} [get_ports {led[6]}]
set_property BOARD_PIN {leds_8bits_tri_o_7} [get_ports {led[7]}]
set_property BOARD_PIN {reset} [get_ports {reset}]
